//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public string Messages1 { get; set; }
        public int MessageTypeId { get; set; }
        public int MessageState { get; set; }
        public System.DateTime MessageTime { get; set; }
    
        public virtual MessageType MessageType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
