//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFtest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Messages = new HashSet<Messages>();
            this.Messages1 = new HashSet<Messages>();
        }
    
        public int Id { get; set; }
        public string LoginPwd { get; set; }
        public string NickName { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public Nullable<int> FaceId { get; set; }
        public Nullable<int> FriendShipPolicyId { get; set; }
        public string Name { get; set; }
        public Nullable<int> StarId { get; set; }
        public Nullable<int> BloodTypeId { get; set; }
    
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Messages> Messages1 { get; set; }
    }
}
