//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public System.DateTime PubDate { get; set; }
        public int Clicks { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
